# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: flake8
      - run:
          name: run tests
          command: coverage run -m pytest
      - run:
          name: Check Test Coverage
          command: |
            coverage=$(coverage report -m | grep TOTAL | awk '{print $4}')
            if [ "$coverage" \< 80 ]; then
              echo "Test coverage is below 80% ($coverage%)"
              exit 1
            fi
  build-docker:
    docker:
      - image: docker:stable
    steps:
      # Checkout the repository files
      - checkout
      # Set up a separate Docker environment to run `docker` commands in
      - setup_remote_docker
      - run:
          name: Build Docker image
          command:
            docker build --tag $IMAGE_TAG .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker tag $IMAGE_TAG:latest $IMAGE_TAG:${CIRCLE_SHA1}
            docker push $IMAGE_TAG:${CIRCLE_SHA1}
            docker push $IMAGE_TAG:latest
  deploy-heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - setup_remote_docker
      - run :
          name: Pull from dockerHub and push Docker image to Heroku
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            docker pull $IMAGE_TAG
            docker tag $IMAGE_TAG:latest registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            heroku container:release -a $HEROKU_APP_NAME web 

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-and-build-workflow:
    jobs:
      - test-and-lint
      - build-docker:
          requires:
            - test-and-lint
          filters:
            branches:
              only:
                - main
                - develop
      - deploy-heroku:
          requires:
            - build-docker
          filters:
            branches:
              only:
                - main